<?php

if (!function_exists('icons')) {
    function icons() {
        // Ícones relacionados ao Negócio e Trabalho
        $business = [
            'fa-solid fa-user-plus' => 'Adicionar usuário', 
            'fa-solid fa-user' => 'Usuário', 
            'fa-solid fa-briefcase' => 'Pasta de trabalho', 
            'fa-solid fa-handshake' => 'Aperto de mãos', 
            'fa-solid fa-building' => 'Edifício', 
            'fa-solid fa-chart-line' => 'Gráfico de linha', 
            'fa-solid fa-users' => 'Usuários', 
            'fa-solid fa-tasks' => 'Tarefas', 
            'fa-solid fa-list' => 'Lista', 
            'fa-solid fa-clipboard' => 'Prancheta',
            'fa-solid fa-project-diagram' => 'Diagrama de projeto', 
            'fa-solid fa-dollar-sign' => 'Símbolo de dólar', 
            'fa-solid fa-coins' => 'Moedas', 
            'fa-solid fa-cogs' => 'Engrenagens', 
            'fa-solid fa-business-time' => 'Horário comercial', 
            'fa-solid fa-money-check-alt' => 'Cheque',
            'fa-solid fa-piggy-bank' => 'Cofrinho', 
            'fa-solid fa-credit-card' => 'Cartão de crédito', 
            'fa-solid fa-industry' => 'Indústria', 
            'fa-solid fa-clipboard-check' => 'Prancheta com verificação', 
            'fa-solid fa-trophy' => 'Troféu', 
            'fa-solid fa-lightbulb' => 'Lâmpada',
            'fa-solid fa-cash-register' => 'Caixa registradora', 
            'fa-solid fa-people-arrows' => 'Pessoas com setas', 
            'fa-solid fa-headset' => 'Headset', 
            'fa-solid fa-rocket' => 'Foguete', 
            'fa-solid fa-house' => 'Casa', 
            'fa-solid fa-arrow-alt-circle-up' => 'Seta para cima em círculo',
            'fa-solid fa-plus' => 'Adicionar',
            'fa-solid fa-angle-up' => 'Seta para cima',
            'fa-solid fa-angle-down' => 'Seta para baixo',
        ];

        // Ícones relacionados à Comunicação e Redes Sociais
        $communication = [
            'fa-solid fa-comment' => 'Comentário',
            'fa-solid fa-envelope' => 'Envelope',
            'fa-solid fa-phone' => 'Telefone',
            'fa-solid fa-comments' => 'Comentários',
            'fa-solid fa-users' => 'Usuários',
            'fa-solid fa-bell' => 'Sino',
            'fa-solid fa-paper-plane' => 'Avião de papel',
            'fa-solid fa-share-alt' => 'Compartilhar',
            'fa-solid fa-chalkboard-teacher' => 'Professor com quadro',
            'fa-solid fa-video' => 'Vídeo',
            'fa-solid fa-quote-left' => 'Aspas esquerda',
            'fa-solid fa-hashtag' => 'Hashtag',
            'fa-solid fa-at' => 'Arroba',
            'fa-solid fa-inbox' => 'Caixa de entrada',
            'fa-solid fa-broadcast-tower' => 'Torre de transmissão',
            'fa-solid fa-podcast' => 'Podcast',
            'fa-solid fa-paperclip' => 'Clipe de papel',
            'fa-solid fa-link' => 'Link',
            'fa-solid fa-share-square' => 'Compartilhar quadrado',
            'fa-solid fa-envelope-open-text' => 'Envelope aberto com texto',
            'fa-solid fa-thumbs-up' => 'Joinha',
            'fa-solid fa-thumbs-down' => 'Joinha negativo',
            'fa-solid fa-retweet' => 'Retweet',
            'fa-solid fa-stream' => 'Fluxo',
            'fa-solid fa-share' => 'Compartilhar',
            'fa-solid fa-sms' => 'SMS',
            'fa-solid fa-user-circle' => 'Círculo de usuário',
            'fa-solid fa-voicemail' => 'Correio de voz'
        ];

        // Ícones relacionados à Tecnologia
        $technology = [
            'fa-solid fa-laptop' => 'Laptop',
            'fa-solid fa-desktop' => 'Desktop',
            'fa-solid fa-tablet-alt' => 'Tablet',
            'fa-solid fa-phone-alt' => 'Telefone',
            'fa-solid fa-keyboard' => 'Teclado',
            'fa-solid fa-cogs' => 'Engrenagens',
            'fa-solid fa-wifi' => 'Wi-Fi',
            'fa-solid fa-cloud' => 'Nuvem',
            'fa-solid fa-server' => 'Servidor',
            'fa-solid fa-database' => 'Banco de dados',
            'fa-solid fa-cogs' => 'Engrenagens',
            'fa-solid fa-camera-retro' => 'Câmera retrô',
            'fa-solid fa-satellite' => 'Satélite',
            'fa-solid fa-charging-station' => 'Estação de carregamento',
            'fa-solid fa-glasses' => 'Óculos',
            'fa-solid fa-battery-full' => 'Bateria cheia',
            'fa-solid fa-battery-half' => 'Bateria média',
            'fa-solid fa-battery-quarter' => 'Bateria baixa',
            'fa-solid fa-battery-empty' => 'Bateria vazia',
            'fa-solid fa-headphones' => 'Headphones',
            'fa-solid fa-plane-up' => 'Avião subindo',
            'fa-solid fa-fax' => 'Fax',
            'fa-solid fa-microchip' => 'Microchip',
            'fa-solid fa-laptop-code' => 'Laptop com código',
            'fa-solid fa-fingerprint' => 'Impressão digital',
            'fa-solid fa-television' => 'Televisão',
            'fa-solid fa-search' => 'Buscar',
            'fa-solid bi bi-robot' => 'Robô'
        ];

        // Ícones relacionados à Segurança
        $security = [
            'fa-solid fa-shield-alt' => 'Escudo',
            'fa-solid fa-lock' => 'Cadeado',
            'fa-solid fa-user-shield' => 'Usuário com escudo',
            'fa-solid fa-lock-open' => 'Cadeado aberto',
            'fa-solid fa-bolt' => 'Raio',
            'fa-solid fa-biohazard' => 'Risco biológico',
            'fa-solid fa-exclamation-triangle' => 'Triângulo de exclamação',
            'fa-solid fa-virus' => 'Vírus',
            'fa-solid fa-fire' => 'Fogo',
            'fa-solid fa-clipboard-check' => 'Prancheta com verificação',
            'fa-solid fa-key' => 'Chave',
            'fa-solid fa-bug' => 'Inseto',
            'fa-solid fa-cogs' => 'Engrenagens',
            'fa-solid fa-eye' => 'Olho',
            'fa-solid fa-eye-slash' => 'Olho riscado',
            'fa-solid fa-fingerprint' => 'Impressão digital',
            'fa-solid fa-user-lock' => 'Usuário com cadeado',
            'fa-solid fa-bell' => 'Sino',
            'fa-solid fa-hand-paper' => 'Mão aberta',
            'fa-solid fa-user-secret' => 'Agente secreto',
            'fa-solid fa-dove' => 'Pomba',
            'fa-solid fa-user-secret' => 'Agente secreto',
            'fa-solid fa-shield-virus' => 'Escudo antiviral',
            'fa-solid fa-cogs' => 'Engrenagens',
            'fa-solid fa-fire-alt' => 'Fogo alternativo',
            'fa-solid fa-exclamation-circle' => 'Círculo de exclamação',
            'fa-solid fa-shield' => 'Escudo',
            'fa-solid fa-ban' => 'Proibido'
        ];

        // Ícones relacionados à Documentação e Arquivos
        $documents = [
            'fa-solid fa-file' => 'Arquivo',
            'fa-solid fa-file-alt' => 'Arquivo de texto',
            'fa-solid fa-file-pdf' => 'Arquivo PDF',
            'fa-solid fa-file-word' => 'Arquivo Word',
            'fa-solid fa-file-excel' => 'Arquivo Excel',
            'fa-solid fa-folder' => 'Pasta',
            'fa-solid fa-file-archive' => 'Arquivo compactado',
            'fa-solid fa-copy' => 'Copiar',
            'fa-solid fa-paperclip' => 'Clipe de papel',
            'fa-solid fa-book' => 'Livro',
            'fa-solid fa-scroll' => 'Pergaminho',
            'fa-solid fa-pencil-alt' => 'Lápis',
            'fa-solid fa-print' => 'Impressora',
            'fa-solid fa-folder-open' => 'Pasta aberta',
            'fa-solid fa-folder-plus' => 'Adicionar pasta',
            'fa-solid fa-bookmark' => 'Marcador',
            'fa-solid fa-clone' => 'Clonar',
            'fa-solid fa-file-image' => 'Arquivo de imagem',
            'fa-solid fa-file-audio' => 'Arquivo de áudio',
            'fa-solid fa-file-video' => 'Arquivo de vídeo',
            'fa-solid fa-file-code' => 'Arquivo de código',
            'fa-solid fa-archive' => 'Arquivo',
            'fa-solid fa-file-signature' => 'Arquivo com assinatura',
            'fa-solid fa-file-upload' => 'Upload de arquivo',
            'fa-solid fa-paper-plane' => 'Avião de papel',
            'fa-solid fa-clipboard' => 'Prancheta',
            'fa-solid fa-folder-minus' => 'Remover pasta',
            'fa-solid fa-cloud-upload-alt' => 'Upload para nuvem'
        ];

        // Ícones relacionados à Saúde e Bem-estar
        $health = [
            'fa-solid fa-user-md' => 'Médico',
            'fa-solid fa-heartbeat' => 'Batimento cardíaco',
            'fa-solid fa-ambulance' => 'Ambulância',
            'fa-solid fa-stethoscope' => 'Estetoscópio',
            'fa-solid fa-pills' => 'Comprimidos',
            'fa-solid fa-baby' => 'Bebê',
            'fa-solid fa-hospital' => 'Hospital',
            'fa-solid fa-medkit' => 'Kit médico',
            'fa-solid fa-syringe' => 'Seringa',
            'fa-solid fa-thermometer' => 'Termômetro',
            'fa-solid fa-tooth' => 'Dente',
            'fa-solid fa-dna' => 'DNA',
            'fa-solid fa-hospital-alt' => 'Hospital alternativo',
            'fa-solid fa-heart' => 'Coração',
            'fa-solid fa-hands-helping' => 'Mãos ajudando',
            'fa-solid fa-user-injured' => 'Usuário ferido',
            'fa-solid fa-user-nurse' => 'Enfermeiro',
            'fa-solid fa-hospital-symbol' => 'Símbolo de hospital',
            'fa-solid fa-flask' => 'Frasco',
            'fa-solid fa-bone' => 'Osso',
            'fa-solid fa-lungs' => 'Pulmões',
            'fa-solid fa-prescription-bottle' => 'Frasco de receita',
            'fa-solid fa-clinic-medical' => 'Clínica médica',
            'fa-solid fa-first-aid' => 'Primeiros socorros',
            'fa-solid fa-hand-holding-medical' => 'Mão segurando símbolo médico',
            'fa-solid fa-weight' => 'Peso',
            'fa-solid fa-stethoscope' => 'Estetoscópio',
            'fa-solid fa-diagnoses' => 'Diagnósticos'
        ];

        // Ícones relacionados ao Ambiente e Sustentabilidade
        $environment = [
            'fa-solid fa-leaf' => 'Folha',
            'fa-solid fa-tree' => 'Árvore',
            'fa-solid fa-water' => 'Água',
            'fa-solid fa-sun' => 'Sol',
            'fa-solid fa-recycle' => 'Reciclagem',
            'fa-solid fa-bicycle' => 'Bicicleta',
            'fa-solid fa-earth-americas' => 'Terra (Américas)',
            'fa-solid fa-globe' => 'Globo',
            'fa-solid fa-wind' => 'Vento',
            'fa-solid fa-solar-panel' => 'Painel solar',
            'fa-solid fa-biohazard' => 'Risco biológico',
            'fa-solid fa-sun' => 'Sol',
            'fa-solid fa-cloud-sun' => 'Nuvem e sol',
            'fa-solid fa-umbrella' => 'Guarda-chuva',
            'fa-solid fa-flask' => 'Frasco',
            'fa-solid fa-wind' => 'Vento',
            'fa-solid fa-snowflake' => 'Floco de neve',
            'fa-solid fa-fire' => 'Fogo',
            'fa-solid fa-bolt' => 'Raio',
            'fa-solid fa-rainbow' => 'Arco-íris',
            'fa-solid fa-mountain' => 'Montanha',
            'fa-solid fa-hands-helping' => 'Mãos ajudando',
            'fa-solid fa-lightbulb' => 'Lâmpada',
            'fa-solid fa-paint-roller' => 'Rolo de pintura',
            'fa-solid fa-battery-full' => 'Bateria cheia',
            'fa-solid fa-battery-empty' => 'Bateria vazia',
            'fa-solid fa-seedling' => 'Muda de planta',
            'fa-solid fa-clover' => 'Trevo'
        ];

        // Ícones de Marcas e Logos (fa-brands)
        $brands = [
            // Redes Sociais e Comunicação
            'fa-brands fa-facebook' => 'Facebook',
            'fa-brands fa-facebook-f' => 'Facebook F',
            'fa-brands fa-facebook-messenger' => 'Facebook Messenger',
            'fa-brands fa-instagram' => 'Instagram',
            'fa-brands fa-whatsapp' => 'WhatsApp',
            'fa-brands fa-x-twitter' => 'X (Twitter)',
            'fa-brands fa-linkedin' => 'LinkedIn',
            'fa-brands fa-linkedin-in' => 'LinkedIn In',
            'fa-brands fa-youtube' => 'YouTube',
            'fa-brands fa-tiktok' => 'TikTok',
            'fa-brands fa-pinterest' => 'Pinterest',
            'fa-brands fa-pinterest-p' => 'Pinterest P',
            'fa-brands fa-snapchat' => 'Snapchat',
            'fa-brands fa-snapchat-ghost' => 'Snapchat Fantasma',
            'fa-brands fa-telegram' => 'Telegram',
            'fa-brands fa-discord' => 'Discord',
            'fa-brands fa-twitch' => 'Twitch',
            'fa-brands fa-reddit' => 'Reddit',
            'fa-brands fa-reddit-alien' => 'Reddit Alien',
            'fa-brands fa-tumblr' => 'Tumblr',
            'fa-brands fa-tumblr-square' => 'Tumblr Quadrado',
            'fa-brands fa-flickr' => 'Flickr',
            'fa-brands fa-vimeo' => 'Vimeo',
            'fa-brands fa-vimeo-v' => 'Vimeo V',
            
            // Tecnologia e Desenvolvimento
            'fa-brands fa-github' => 'GitHub',
            'fa-brands fa-github-alt' => 'GitHub Alternativo',
            'fa-brands fa-gitlab' => 'GitLab',
            'fa-brands fa-bitbucket' => 'Bitbucket',
            'fa-brands fa-stack-overflow' => 'Stack Overflow',
            'fa-brands fa-stack-exchange' => 'Stack Exchange',
            'fa-brands fa-codepen' => 'CodePen',
            'fa-brands fa-codesandbox' => 'CodeSandbox',
            'fa-brands fa-dev' => 'Dev',
            'fa-brands fa-hackerrank' => 'HackerRank',
            'fa-brands fa-python' => 'Python',
            'fa-brands fa-js' => 'JavaScript',
            'fa-brands fa-php' => 'PHP',
            'fa-brands fa-java' => 'Java',
            'fa-brands fa-swift' => 'Swift',
            'fa-brands fa-rust' => 'Rust',
            'fa-brands fa-golang' => 'Go',
            'fa-brands fa-linux' => 'Linux',
            'fa-brands fa-ubuntu' => 'Ubuntu',
            'fa-brands fa-windows' => 'Windows',
            'fa-brands fa-apple' => 'Apple',
            'fa-brands fa-android' => 'Android',
            
            // Serviços e Negócios
            'fa-brands fa-google' => 'Google',
            'fa-brands fa-google-drive' => 'Google Drive',
            'fa-brands fa-google-pay' => 'Google Pay',
            'fa-brands fa-google-play' => 'Google Play',
            'fa-brands fa-amazon' => 'Amazon',
            'fa-brands fa-amazon-pay' => 'Amazon Pay',
            'fa-brands fa-microsoft' => 'Microsoft',
            'fa-brands fa-paypal' => 'PayPal',
            'fa-brands fa-stripe' => 'Stripe',
            'fa-brands fa-visa' => 'Visa',
            'fa-brands fa-mastercard' => 'Mastercard',
            'fa-brands fa-cc-visa' => 'Cartão Visa',
            'fa-brands fa-cc-mastercard' => 'Cartão Mastercard',
            'fa-brands fa-cc-amex' => 'Cartão American Express',
            'fa-brands fa-cc-paypal' => 'Cartão PayPal',
            'fa-brands fa-cc-stripe' => 'Cartão Stripe',
            'fa-brands fa-uber' => 'Uber',
            'fa-brands fa-airbnb' => 'Airbnb',
            'fa-brands fa-spotify' => 'Spotify',
            'fa-brands fa-soundcloud' => 'SoundCloud',
            'fa-brands fa-dropbox' => 'Dropbox',
            
            // Frameworks e CMS
            'fa-brands fa-wordpress' => 'WordPress',
            'fa-brands fa-joomla' => 'Joomla',
            'fa-brands fa-drupal' => 'Drupal',
            'fa-brands fa-bootstrap' => 'Bootstrap',
            'fa-brands fa-tailwind' => 'Tailwind CSS',
            'fa-brands fa-laravel' => 'Laravel',
            'fa-brands fa-react' => 'React',
            'fa-brands fa-vuejs' => 'Vue.js',
            'fa-brands fa-angular' => 'Angular',
            'fa-brands fa-node' => 'Node.js',
            'fa-brands fa-npm' => 'NPM',
            'fa-brands fa-docker' => 'Docker',
            'fa-brands fa-kubernetes' => 'Kubernetes',
            
            // Outras marcas populares
            'fa-brands fa-medium' => 'Medium',
            'fa-brands fa-quora' => 'Quora',
            'fa-brands fa-stackpath' => 'StackPath',
            'fa-brands fa-digg' => 'Digg',
            'fa-brands fa-delicious' => 'Delicious',
            'fa-brands fa-behance' => 'Behance',
            'fa-brands fa-dribbble' => 'Dribbble',
            'fa-brands fa-figma' => 'Figma',
            'fa-brands fa-canva' => 'Canva',
            'fa-brands fa-adobe' => 'Adobe',
            'fa-brands fa-cc' => 'Creative Commons'
        ];

        // Agrupando as categorias de ícones
        $categoriesIcons = [
            [
                'icone' => '<i class="fa-solid fa-briefcase fs-2"></i>',
                'titulo' => 'Negócios e Trabalho',
                'icones' => $business,
            ],
            [
                'icone' => '<i class="fa-solid fa-comment fs-2"></i>',
                'titulo' => 'Comunicação e Redes Sociais',
                'icones' => $communication,
            ],
            [
                'icone' => '<i class="fa-solid fa-laptop fs-2"></i>',
                'titulo' => 'Tecnologia',
                'icones' => $technology,
            ],
            [
                'icone' => '<i class="fa-solid fa-shield-alt fs-2"></i>',
                'titulo' => 'Segurança',
                'icones' => $security,
            ],
            [
                'icone' => '<i class="fa-solid fa-file fs-2"></i>',
                'titulo' => 'Documentação e Arquivos',
                'icones' => $documents,
            ],
            [
                'icone' => '<i class="fa-solid fa-user-md fs-2"></i>',
                'titulo' => 'Saúde e Bem-estar',
                'icones' => $health,
            ],
            [
                'icone' => '<i class="fa-solid fa-leaf fs-2"></i>',
                'titulo' => 'Ambiente e Sustentabilidade',
                'icones' => $environment,
            ],
            [
                'icone' => '<i class="fa-brands fa-font-awesome fs-2"></i>',
                'titulo' => 'Marcas e Logos',
                'icones' => $brands,
            ],
        ];

        return $categoriesIcons;
    }

}

